// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'invite_contest_response.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

InviteContestData _$InviteContestDataFromJson(Map<String, dynamic> json) =>
    InviteContestData(
      status: (json['status'] as num?)?.toInt(),
      result: json['result'] == null
          ? null
          : Result.fromJson(json['result'] as Map<String, dynamic>),
    );

Map<String, dynamic> _$InviteContestDataToJson(InviteContestData instance) =>
    <String, dynamic>{
      'status': instance.status,
      'result': instance.result,
    };

Result _$ResultFromJson(Map<String, dynamic> json) => Result(
      contest: (json['contest'] as List<dynamic>?)
          ?.map((e) => ContestInvite.fromJson(e as Map<String, dynamic>))
          .toList(),
      user_teams: (json['user_teams'] as num?)?.toInt(),
      joined_leagues: (json['joined_leagues'] as num?)?.toInt(),
      user_balance: json['user_balance'] == null
          ? null
          : UserBalance.fromJson(json['user_balance'] as Map<String, dynamic>),
      sport_key: json['sport_key'] as String?,
      fantasy_type_id: json['fantasy_type_id'] as String?,
      users_matches: (json['users_matches'] as List<dynamic>?)
          ?.map((e) => UsersMatches.fromJson(e as Map<String, dynamic>))
          .toList(),
      user_team_id: (json['user_team_id'] as List<dynamic>?)
          ?.map((e) => (e as num).toInt())
          .toList(),
    )..teams = (json['teams'] as List<dynamic>?)
        ?.map((e) => Teams.fromJson(e as Map<String, dynamic>))
        .toList();

Map<String, dynamic> _$ResultToJson(Result instance) => <String, dynamic>{
      'contest': instance.contest,
      'users_matches': instance.users_matches,
      'user_team_id': instance.user_team_id,
      'teams': instance.teams,
      'user_teams': instance.user_teams,
      'joined_leagues': instance.joined_leagues,
      'user_balance': instance.user_balance,
      'sport_key': instance.sport_key,
      'fantasy_type_id': instance.fantasy_type_id,
    };

ContestInvite _$ContestInviteFromJson(Map<String, dynamic> json) =>
    ContestInvite(
      id: (json['id'] as num?)?.toInt(),
      challenge_id: (json['challenge_id'] as num?)?.toInt(),
      name: json['name'] as String?,
      challenge_type: json['challenge_type'] as String?,
      winning_percentage: (json['winning_percentage'] as num?)?.toInt(),
      challenge_status: json['challenge_status'] as String?,
      challenge_text: json['challenge_text'] as String?,
      entryfee: json['entryfee'] as String?,
      winning_amount: json['winning_amount'] as String?,
      win_amount: (json['win_amount'] as num?)?.toInt(),
      maximum_user: (json['maximum_user'] as num?)?.toInt(),
      getjoinedpercentage: (json['getjoinedpercentage'] as num?)?.toInt(),
      winners: json['winners'],
      userid: (json['userid'] as num?)?.toInt(),
      userrank: (json['userrank'] as num?)?.toInt(),
      team_id: (json['team_id'] as num?)?.toInt(),
      join_id: (json['join_id'] as num?)?.toInt(),
      matchkey: json['matchkey'] as String?,
      joinedusers: (json['joinedusers'] as num?)?.toInt(),
      team1display: json['team1display'] as String?,
      team2display: json['team2display'] as String?,
      multi_entry: (json['multi_entry'] as num?)?.toInt(),
      confirmed_challenge: (json['confirmed_challenge'] as num?)?.toInt(),
      is_running: (json['is_running'] as num?)?.toInt(),
      is_free: (json['is_free'] as num?)?.toInt(),
      is_champion: (json['is_champion'] as num?)?.toInt(),
      champion_player: json['champion_player'] as String?,
      champion_x: json['champion_x'] as String?,
      is_offer_team: (json['is_offer_team'] as num?)?.toInt(),
      dis_price: json['dis_price'] as String?,
      is_bonus: (json['is_bonus'] as num?)?.toInt(),
      is_gstbonus: (json['is_gstbonus'] as num?)?.toInt(),
      bonus_percent: json['bonus_percent'] as String?,
      isselected: json['isselected'] as bool?,
      isselectedid: json['isselectedid'] as String?,
      joinedleagueskey: (json['joinedleagueskey'] as num?)?.toInt(),
      points: (json['points'] as num?)?.toInt(),
      isjoined: json['isjoined'] as bool?,
      joinWith: (json['joinWith'] as num?)?.toInt(),
      refercode: json['refercode'] as String?,
      totalwinners: json['totalwinners'],
      first_rank_prize: (json['first_rank_prize'] as num?)?.toInt(),
      user_joined_count: (json['user_joined_count'] as num?)?.toInt(),
      max_team_limit: (json['max_team_limit'] as num?)?.toInt(),
      max_multi_entry_user: (json['max_multi_entry_user'] as num?)?.toInt(),
      pdf: json['pdf'] as String?,
      is_giveaway_text: json['is_giveaway_text'] as String?,
      is_giveaway_visible_text:
          (json['is_giveaway_visible_text'] as num?)?.toInt(),
      giveaway_color: json['giveaway_color'] as String?,
      announcement: json['announcement'] as String?,
      is_gadget: (json['is_gadget'] as num?)?.toInt(),
      is_flexible: (json['is_flexible'] as num?)?.toInt(),
      is_join_similar_contest:
          (json['is_join_similar_contest'] as num?)?.toInt(),
      myjoin_similar_contest: (json['myjoin_similar_contest'] as num?)?.toInt(),
      gadget_image: json['gadget_image'] as String?,
      user_image: json['user_image'] as String?,
      challenge_category_id: (json['challenge_category_id'] as num?)?.toInt(),
      max_team_limit_exceeded_count:
          (json['max_team_limit_exceeded_count'] as num?)?.toInt(),
      is_winning_zone: (json['is_winning_zone'] as num?)?.toInt(),
      unlimited_credits_contest:
          (json['unlimited_credits_contest'] as num?)?.toInt(),
    );

Map<String, dynamic> _$ContestInviteToJson(ContestInvite instance) =>
    <String, dynamic>{
      'id': instance.id,
      'challenge_id': instance.challenge_id,
      'name': instance.name,
      'challenge_type': instance.challenge_type,
      'winning_percentage': instance.winning_percentage,
      'challenge_status': instance.challenge_status,
      'challenge_text': instance.challenge_text,
      'entryfee': instance.entryfee,
      'winning_amount': instance.winning_amount,
      'win_amount': instance.win_amount,
      'maximum_user': instance.maximum_user,
      'getjoinedpercentage': instance.getjoinedpercentage,
      'winners': instance.winners,
      'userid': instance.userid,
      'userrank': instance.userrank,
      'team_id': instance.team_id,
      'join_id': instance.join_id,
      'matchkey': instance.matchkey,
      'joinedusers': instance.joinedusers,
      'team1display': instance.team1display,
      'team2display': instance.team2display,
      'multi_entry': instance.multi_entry,
      'confirmed_challenge': instance.confirmed_challenge,
      'is_running': instance.is_running,
      'is_free': instance.is_free,
      'is_champion': instance.is_champion,
      'champion_player': instance.champion_player,
      'champion_x': instance.champion_x,
      'is_offer_team': instance.is_offer_team,
      'dis_price': instance.dis_price,
      'is_bonus': instance.is_bonus,
      'is_gstbonus': instance.is_gstbonus,
      'bonus_percent': instance.bonus_percent,
      'isselected': instance.isselected,
      'isselectedid': instance.isselectedid,
      'joinedleagueskey': instance.joinedleagueskey,
      'points': instance.points,
      'isjoined': instance.isjoined,
      'joinWith': instance.joinWith,
      'refercode': instance.refercode,
      'totalwinners': instance.totalwinners,
      'first_rank_prize': instance.first_rank_prize,
      'user_joined_count': instance.user_joined_count,
      'max_team_limit': instance.max_team_limit,
      'max_multi_entry_user': instance.max_multi_entry_user,
      'pdf': instance.pdf,
      'is_giveaway_text': instance.is_giveaway_text,
      'is_giveaway_visible_text': instance.is_giveaway_visible_text,
      'giveaway_color': instance.giveaway_color,
      'announcement': instance.announcement,
      'is_gadget': instance.is_gadget,
      'is_flexible': instance.is_flexible,
      'is_join_similar_contest': instance.is_join_similar_contest,
      'myjoin_similar_contest': instance.myjoin_similar_contest,
      'gadget_image': instance.gadget_image,
      'user_image': instance.user_image,
      'challenge_category_id': instance.challenge_category_id,
      'max_team_limit_exceeded_count': instance.max_team_limit_exceeded_count,
      'is_winning_zone': instance.is_winning_zone,
      'unlimited_credits_contest': instance.unlimited_credits_contest,
    };

UserBalance _$UserBalanceFromJson(Map<String, dynamic> json) => UserBalance(
      winning: (json['winning'] as num?)?.toDouble(),
      balance: json['balance'],
      bonus: (json['bonus'] as num?)?.toInt(),
    );

Map<String, dynamic> _$UserBalanceToJson(UserBalance instance) =>
    <String, dynamic>{
      'winning': instance.winning,
      'balance': instance.balance,
      'bonus': instance.bonus,
    };

UsersMatches _$UsersMatchesFromJson(Map<String, dynamic> json) => UsersMatches(
      id: (json['id'] as num?)?.toInt(),
      name: json['name'] as String?,
      short_name: json['short_name'] as String?,
      time_diff: json['time_diff'] as String?,
      format: json['format'] as String?,
      series: (json['series'] as num?)?.toInt(),
      seriesname: json['seriesname'] as String?,
      toss: json['toss'] as String?,
      team1display: json['team1display'] as String?,
      team2display: json['team2display'] as String?,
      team1name: json['team1name'] as String?,
      team2name: json['team2name'] as String?,
      is_fav_pin_contest: (json['is_fav_pin_contest'] as num?)?.toInt(),
      matchkey: json['matchkey'] as String?,
      winnerstatus: json['winnerstatus'] as String?,
      launch_status: json['launch_status'] as String?,
      match_status_key: (json['match_status_key'] as num?)?.toInt(),
      match_status: json['match_status'] as String?,
      sport_key: json['sport_key'] as String?,
      joined_count: (json['joined_count'] as num?)?.toInt(),
      team_count: (json['team_count'] as num?)?.toInt(),
      winning_total: (json['winning_total'] as num?)?.toInt(),
      total_earned: (json['total_earned'] as num?)?.toInt(),
      final_status: json['final_status'] as String?,
      url: json['url'] as String?,
      banner_image: json['banner_image'] as String?,
      team1logo: json['team1logo'] as String?,
      team2logo: json['team2logo'] as String?,
      lineup: (json['lineup'] as num?)?.toInt(),
      matchindexing: json['matchindexing'] as String?,
      start_date: json['start_date'] as String?,
      time_start: json['time_start'] as String?,
      highlights: json['highlights'] as String?,
      is_leaderboard: (json['is_leaderboard'] as num?)?.toInt(),
      team1_color: json['team1_color'] as String?,
      team2_color: json['team2_color'] as String?,
      is_fiveplusone: (json['is_fiveplusone'] as num?)?.toInt(),
      is_tenplusone: (json['is_tenplusone'] as num?)?.toInt(),
      is_amount_show: (json['is_amount_show'] as num?)?.toInt(),
      secondinning: (json['secondinning'] as num?)?.toInt(),
      amount: json['amount'] as String?,
      fantasy_type_id: (json['fantasy_type_id'] as num?)?.toInt(),
      unlimited_credit_match: (json['unlimited_credit_match'] as num?)?.toInt(),
      unlimited_credit_text: json['unlimited_credit_text'] as String?,
      is_classic_format: (json['is_classic_format'] as num?)?.toInt(),
      is_fiveplusOne_format: (json['is_fiveplusOne_format'] as num?)?.toInt(),
      is_TenplusOne_format: (json['is_TenplusOne_format'] as num?)?.toInt(),
    );

Map<String, dynamic> _$UsersMatchesToJson(UsersMatches instance) =>
    <String, dynamic>{
      'id': instance.id,
      'name': instance.name,
      'short_name': instance.short_name,
      'time_diff': instance.time_diff,
      'format': instance.format,
      'series': instance.series,
      'seriesname': instance.seriesname,
      'toss': instance.toss,
      'team1display': instance.team1display,
      'team2display': instance.team2display,
      'team1name': instance.team1name,
      'team2name': instance.team2name,
      'is_fav_pin_contest': instance.is_fav_pin_contest,
      'matchkey': instance.matchkey,
      'winnerstatus': instance.winnerstatus,
      'launch_status': instance.launch_status,
      'match_status_key': instance.match_status_key,
      'match_status': instance.match_status,
      'sport_key': instance.sport_key,
      'joined_count': instance.joined_count,
      'team_count': instance.team_count,
      'winning_total': instance.winning_total,
      'total_earned': instance.total_earned,
      'final_status': instance.final_status,
      'url': instance.url,
      'banner_image': instance.banner_image,
      'team1logo': instance.team1logo,
      'team2logo': instance.team2logo,
      'lineup': instance.lineup,
      'matchindexing': instance.matchindexing,
      'start_date': instance.start_date,
      'time_start': instance.time_start,
      'highlights': instance.highlights,
      'is_leaderboard': instance.is_leaderboard,
      'team1_color': instance.team1_color,
      'team2_color': instance.team2_color,
      'is_fiveplusone': instance.is_fiveplusone,
      'is_tenplusone': instance.is_tenplusone,
      'is_amount_show': instance.is_amount_show,
      'secondinning': instance.secondinning,
      'amount': instance.amount,
      'fantasy_type_id': instance.fantasy_type_id,
      'unlimited_credit_match': instance.unlimited_credit_match,
      'unlimited_credit_text': instance.unlimited_credit_text,
      'is_classic_format': instance.is_classic_format,
      'is_fiveplusOne_format': instance.is_fiveplusOne_format,
      'is_TenplusOne_format': instance.is_TenplusOne_format,
    };

Teams _$TeamsFromJson(Map<String, dynamic> json) => Teams(
      teamnumber: (json['teamnumber'] as num?)?.toInt(),
      teamid: (json['teamid'] as num?)?.toInt(),
      points: (json['points'] as num?)?.toInt(),
      matchkey: json['matchkey'] as String?,
      fantasy_type_id: (json['fantasy_type_id'] as num?)?.toInt(),
      fantasytype: json['fantasytype'] as String?,
      team1_name: json['team1_name'] as String?,
      team2_name: json['team2_name'] as String?,
      is_joined: (json['is_joined'] as num?)?.toInt(),
      join_id: (json['join_id'] as num?)?.toInt(),
      players: (json['players'] as List<dynamic>?)
          ?.map((e) => Players.fromJson(e as Map<String, dynamic>))
          .toList(),
      team1_player_count: (json['team1_player_count'] as num?)?.toInt(),
      team2_player_count: (json['team2_player_count'] as num?)?.toInt(),
      is_non_playing_players: (json['is_non_playing_players'] as num?)?.toInt(),
      is_non_playing_players_text:
          json['is_non_playing_players_text'] as String?,
    );

Map<String, dynamic> _$TeamsToJson(Teams instance) => <String, dynamic>{
      'teamnumber': instance.teamnumber,
      'teamid': instance.teamid,
      'points': instance.points,
      'matchkey': instance.matchkey,
      'fantasy_type_id': instance.fantasy_type_id,
      'fantasytype': instance.fantasytype,
      'team1_name': instance.team1_name,
      'team2_name': instance.team2_name,
      'is_joined': instance.is_joined,
      'join_id': instance.join_id,
      'players': instance.players,
      'team1_player_count': instance.team1_player_count,
      'team2_player_count': instance.team2_player_count,
      'is_non_playing_players': instance.is_non_playing_players,
      'is_non_playing_players_text': instance.is_non_playing_players_text,
    };

Players _$PlayersFromJson(Map<String, dynamic> json) => Players(
      id: (json['id'] as num?)?.toInt(),
      matchkey: json['matchkey'] as String?,
      name: json['name'] as String?,
      role: json['role'] as String?,
      short_role: json['short_role'] as String?,
      display_role: json['display_role'] as String?,
      credit: json['credit'] as String?,
      last_match: (json['last_match'] as num?)?.toInt(),
      last_match_text: json['last_match_text'] as String?,
      team: json['team'] as String?,
      teamcode: json['teamcode'] as String?,
      last_match_played_info_text:
          json['last_match_played_info_text'] as String?,
      is_visible_last_match_played:
          (json['is_visible_last_match_played'] as num?)?.toInt(),
      teamcolor: json['teamcolor'] as String?,
      image: json['image'] as String?,
      vicecaptain: (json['vicecaptain'] as num?)?.toInt(),
      captain: (json['captain'] as num?)?.toInt(),
      points: (json['points'] as num?)?.toInt(),
      is_playing: (json['is_playing'] as num?)?.toInt(),
      is_playing_show: (json['is_playing_show'] as num?)?.toInt(),
      series_points: json['series_points'] as String?,
      selected_by: json['selected_by'] as String?,
      vice_captain_selected_by: json['vice_captain_selected_by'] as String?,
      captain_selected_by: json['captain_selected_by'] as String?,
      batting_order: json['batting_order'] as String?,
    );

Map<String, dynamic> _$PlayersToJson(Players instance) => <String, dynamic>{
      'id': instance.id,
      'matchkey': instance.matchkey,
      'name': instance.name,
      'role': instance.role,
      'short_role': instance.short_role,
      'display_role': instance.display_role,
      'credit': instance.credit,
      'last_match': instance.last_match,
      'last_match_text': instance.last_match_text,
      'team': instance.team,
      'teamcode': instance.teamcode,
      'last_match_played_info_text': instance.last_match_played_info_text,
      'is_visible_last_match_played': instance.is_visible_last_match_played,
      'teamcolor': instance.teamcolor,
      'image': instance.image,
      'vicecaptain': instance.vicecaptain,
      'captain': instance.captain,
      'points': instance.points,
      'is_playing': instance.is_playing,
      'is_playing_show': instance.is_playing_show,
      'series_points': instance.series_points,
      'selected_by': instance.selected_by,
      'vice_captain_selected_by': instance.vice_captain_selected_by,
      'captain_selected_by': instance.captain_selected_by,
      'batting_order': instance.batting_order,
    };
